[build]
  command = "npm run build"
  publish = "dist"
  [build.environment]
    NODE_OPTIONS = "--max-old-space-size=4096"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 